NAME = exo_03

CC = clang++

SRC = ./main.cpp \
	./HumanA.cpp \
	./Weapon.cpp \
	./HumanB.cpp \

all: $(NAME)

$(NAME): $(SRC)
	$(CC) $(SRC) -o $(NAME)

clean:
	rm -rf $(NAME)

fclean:
	rm -rf $(NAME)
